/*
 * TinyML Neural Network - hand-written forward pass for Seeed Wio Terminal.
 *
 * Headers in this folder (generated by Python, then #included here):
 *   wio_int8_weights_nano.h    ←  py -3.12 scripts/prepare_wio_nano.py
 *   wio_int8_weights_tiny.h    ←  py -3.12 scripts/prepare_wio_tiny.py
 *   wio_int8_weights_small.h   ←  py -3.12 scripts/prepare_wio_small.py
 *   wio_int8_weights_medium.h  ←  py -3.12 scripts/prepare_wio_medium.py
 *   fen_input.h               ←  py -3.12 scripts/fen_to_c_array.py "FEN" --output Arduino/Wio_TinyValueTest/fen_input.h
 *
 * Architecture (FC*_IN/OUT_DIM) and int8 weights come from the active WEIGHTS_FILE.
 * Upload: Board = Seeed Wio Terminal, Port = your COM port, Serial = 115200.
 */

// ===== Model file =====
// Swap the active line to switch models (header must exist in this folder).
// #define WEIGHTS_FILE "wio_int8_weights_nano.h"     // 768→16→8→1   (~12.5k params)
// #define WEIGHTS_FILE "wio_int8_weights_tiny.h"     // 768→32→16→1  (~25k params)
#define WEIGHTS_FILE "wio_int8_weights_small.h"    // 768→64→32→1   (~51k params)
// #define WEIGHTS_FILE "wio_int8_weights_medium.h"   // 768→128→64→1 (~104k params)
// #define WEIGHTS_FILE "wio_int8_weights_big.h"
// #define WEIGHTS_FILE "wio_int8_weights_huge.h"

#include WEIGHTS_FILE
#include "fen_input.h"
#include <math.h>
#include <avr/pgmspace.h>

#include <TFT_eSPI.h>
#include <SPI.h>

TFT_eSPI tft = TFT_eSPI();

// Prevents the compiler from eliminating forward() in the stress loop (-Os dead-code removal).
static volatile float forwardSink = 0.0f;

// Int8 quantized forward pass (weights from the file named by WEIGHTS_FILE, scales applied on-the-fly)
// Input x is float 0/1 (from fen_input.h). We treat input_scale = 1.0
// This approximates the original float32 model while using 4x less weight memory.
float forward(const float* x) {
  
  // --- LAYER 1 (Input -> Hidden 1) ---
  float h1[FC1_OUT_DIM];
  for (int i = 0; i < FC1_OUT_DIM; i++) {
    int32_t acc = 0;
    for (int j = 0; j < FC1_IN_DIM; j++) {
      int8_t wq = pgm_read_byte(&fc1_w[i * FC1_IN_DIM + j]);
      int8_t xq = (x[j] > 0.5f ? 1 : 0);
      acc += (int32_t)wq * xq;
    }
    float sum = (float)acc * fc1_w_scale * input_scale;
    int8_t bq = pgm_read_byte(&fc1_b[i]);
    sum += (float)bq * fc1_b_scale;
    h1[i] = (sum > 0.0f) ? sum : 0.0f; // ReLU
  }

  // --- LAYER 2 (Hidden 1 -> Hidden 2) ---
  float h2[FC2_OUT_DIM];
  for (int i = 0; i < FC2_OUT_DIM; i++) {
    int32_t acc = 0;
    for (int j = 0; j < FC2_IN_DIM; j++) {
      int8_t wq = pgm_read_byte(&fc2_w[i * FC2_IN_DIM + j]);
      int8_t xq = (h1[j] > 0.5f ? 1 : 0); // requantize activation roughly
      acc += (int32_t)wq * xq;
    }
    float sum = (float)acc * fc2_w_scale; // input_scale for this layer approximated
    int8_t bq = pgm_read_byte(&fc2_b[i]);
    sum += (float)bq * fc2_b_scale;
    h2[i] = (sum > 0.0f) ? sum : 0.0f; // ReLU
  }

  // --- LAYER 3 (Hidden 2 -> Output) ---
  int32_t acc = 0;
  for (int j = 0; j < FC3_IN_DIM; j++) {
    int8_t wq = pgm_read_byte(&fc3_w[j]);
    int8_t xq = (h2[j] > 0.5f ? 1 : 0);
    acc += (int32_t)wq * xq;
  }
  float out = (float)acc * fc3_w_scale;
  int8_t bq = pgm_read_byte(&fc3_b[0]);
  out += (float)bq * fc3_b_scale;
  return tanhf(out);
}

void setup() {
  Serial.begin(115200);
  // Wait up to 3s for USB Serial (don't block forever on battery power)
  unsigned long serialWait = millis();
  while (!Serial && millis() - serialWait < 3000) { }

  Serial.print("Loaded Weights File: ");
  Serial.println(WEIGHTS_FILE);
  Serial.print("Architecture: ");
  Serial.print(FC1_IN_DIM); Serial.print("→"); Serial.print(FC1_OUT_DIM);
  Serial.print("→"); Serial.print(FC2_OUT_DIM);
  Serial.print("→"); Serial.println(FC3_OUT_DIM);

  // Also print first 3 weights to Serial (to cross-check with LCD)
  // Cast via int8_t first so negative values print correctly (pgm_read_byte returns uint8_t)
  Serial.print("First 3 weights from fc1_w: ");
  Serial.print((int)(int8_t)pgm_read_byte(&fc1_w[0]));
  Serial.print(",");
  Serial.print((int)(int8_t)pgm_read_byte(&fc1_w[1]));
  Serial.print(",");
  Serial.println((int)(int8_t)pgm_read_byte(&fc1_w[2]));

  tft.init();
  tft.setRotation(3);
  tft.fillScreen(TFT_BLACK);
  tft.setTextColor(TFT_WHITE);

  // Print filename to TFT display at the bottom (y=70)
  tft.setTextSize(1); // Smaller text size for long filenames
  tft.setCursor(10, 90);
  tft.print("Weights: ");
  tft.print(WEIGHTS_FILE);

  // Print first 3 weights (from fc1_w) in small text to verify we are actually loading/using the int8 data
  tft.setCursor(10, 110);
  tft.print("W[0:2]:");
  tft.print((int)(int8_t)pgm_read_byte(&fc1_w[0]));
  tft.print(",");
  tft.print((int)(int8_t)pgm_read_byte(&fc1_w[1]));
  tft.print(",");
  tft.print((int)(int8_t)pgm_read_byte(&fc1_w[2]));

  tft.setTextSize(2);
  tft.setCursor(10, 10);
  tft.print("Inferred value:");

  // One-shot parity check on the FEN in fen_input.h
  float val = forward(input);
  Serial.print("Inferred value: ");
  Serial.println(val, 6);

  tft.setCursor(10, 30);
  tft.print(val, 6);
}

// EMA smoothing: 0 = show raw per-interval rate, 0.85 = gentle smoothing
static const float kEmaDecay = 0.8f;

void loop() {
  // Stress test: one real forward pass per iteration; report every 1s
  forwardSink = forward(input);

  static unsigned long evals = 0;
  static unsigned long evalsAtLastReport = 0;
  static unsigned long lastReport = 0;
  static float smoothedEvalsPerSec = 0.0f;
  static bool hasSmoothed = false;
  static bool skipWarmupInterval = true;  // discard first 1s window (often inflated)

  evals++;
  unsigned long now = millis();

  if (!lastReport) {
    lastReport = now;
    evalsAtLastReport = 0;
  }

  if (now - lastReport >= 1000) {
    unsigned long dtMs = now - lastReport;
    unsigned long deltaEvals = evals - evalsAtLastReport;
    float instantRate = (dtMs > 0)
      ? (1000.0f * (float)deltaEvals / (float)dtMs)
      : 0.0f;

    if (skipWarmupInterval) {
      // Seed EMA from first full interval but don't display yet
      smoothedEvalsPerSec = instantRate;
      hasSmoothed = true;
      skipWarmupInterval = false;
    } else {
      if (!hasSmoothed) {
        smoothedEvalsPerSec = instantRate;
        hasSmoothed = true;
      } else {
        smoothedEvalsPerSec = kEmaDecay * smoothedEvalsPerSec
                            + (1.0f - kEmaDecay) * instantRate;
      }

      Serial.print("Avg Evals/s: ");
      Serial.print(smoothedEvalsPerSec, 2);
      Serial.println("K");

      tft.fillRect(110, 60, 200, 16, TFT_BLACK);
      tft.setCursor(10, 60);
      tft.print("Avg Evals/s: ");
      tft.print(smoothedEvalsPerSec, 2);
      tft.println("K");
    }

    evalsAtLastReport = evals;
    lastReport = now;
  }
}
